# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [ ]:
import numpy as np
np.__version__

'1.18.5'



---



## 배열 생성

### 리스트로 배열 만들기


In [ ]:
#1차원
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [ ]:
#2차원
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 1], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [ ]:
#3차원
a3 = np.array([ [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
                [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
                [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ] ])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [ ]:
np.full((3, 3), 1.23) #np.full(shape, fill_value(=초기값))

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [ ]:
np.eye(3) #단위행렬은 정사각행렬이니 길이만 지정

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [ ]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [ ]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [ ]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [ ]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [ ]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [ ]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [ ]:
np.random.random((3, 3))

array([[0.0155269 , 0.8969254 , 0.57104967],
       [0.20013507, 0.41798655, 0.41403103],
       [0.20058515, 0.10337014, 0.12161406]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [ ]:
np.random.randint(0, 10, (3, 3))

array([[0, 6, 5],
       [4, 3, 5],
       [7, 9, 4]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [ ]:
np.random.normal(0, 1, (3, 3))

array([[-0.82119193,  0.13736289,  0.74398084],
       [-2.27120876, -0.10593695,  1.15900374],
       [ 1.42029411,  0.63219364,  0.30978055]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.rand(3, 3)

array([[0.83233927, 0.0629179 , 0.24262402],
       [0.41271746, 0.01041742, 0.2954081 ],
       [0.05421773, 0.46080594, 0.40413417]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.randn(3, 3)

array([[ 0.3678534 , -1.49049054,  0.25837326],
       [-0.23612322, -0.87938074, -0.80288913],
       [ 0.09348568,  1.15602997, -0.45088362]])

### 표준 데이터 타입

In [ ]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3, 3), dtype=bool) #1은 True

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3, 3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [ ]:
date = np.array('2020-01-01', dtype = np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [ ]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns') #나노초
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [ ]:
def array_info(array):
  print(array)
  print("nidm:", array.ndim)
  print("shape:", array.shape)
  print("dtype:", array.dtype)
  print("size:", array.size)
  print("itemsize:", array.itemsize) #itemsize: 하나의 아이템이 가지는 사이즈(byte)
  print("nbytes:", array.nbytes) #nbytes: 전체사이즈 (itemsize * item 개수)
  print("strides:", array.strides) #strides: 다음 차원으로 넘어가기 위해 필요한 사이즈

In [ ]:
array_info(a1)

[4 5 6 4 5]
nidm: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [ ]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
nidm: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [ ]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
nidm: 3
shape: (3, 3, 3)
dtype: int64
size: 27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)


### 인덱싱(Indexing)

In [ ]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [ ]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, 1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [ ]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[2, 2, 2])
print(a3[2, -1, -1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [ ]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1]) #reverse

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [ ]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [ ]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [ ]:
print(a2)
bi = np.random.randint(0, 2, (3, 3), dtype = bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [ True  True False]
 [ True  True False]]
[2 4 5 7 8]


### 팬시 인덱싱(Fancy Indedxing)

In [ ]:
print(a1)
print([a1[0], a1[2]])
ind = [0, 2]
print(a1[ind])
ind = np.array([[0, 1],
                [2, 0]]) #인덱스에 따라 배열의 shape 결정
print(a1[ind])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [ ]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
print(a1)
b1 = np.insert(a1, 0, 10) #np.insert(array, 위치, 값)
print(b1)
print(a1) #원본 배열은 변경 X
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[4 5 6 4 5]
[ 4  5 10  6  4  5]


In [ ]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0) #axis=0: 세로
print(b2)
c2 = np.insert(a2, 1, 10, axis=1) #axis=1: 가로
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [ ]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4]) #fancy indexing
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[9 0 3 0 0]
[1 2 3 0 0]
[9 2 3 0 0]
[9 0 3 0 0]
[9 4 3 4 4]


In [ ]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1
print(a2)
a2[1:, 2] = 9
print(a2)
row = np.array([0, 1]) #fancy indexing
col = np.array([1, 2])
a2[row, col] = 0
print(a2)

[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 1 1]
 [4 2 9]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [ ]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [ ]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)
print(a2) #원본 배열이 바뀜

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [ ]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, :1] = 1
print(a2_sub_copy)
print(a2) #명시적으로 copy() 사용해 복사했기 때문에 원본 배열에 영향 X

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 0]
 [1 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [ ]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [ ]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [ ]:
print(a2)
print(a2.swapaxes(1, 0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [ ]:
print(a3)
print(a3.swapaxes(0, 1))
print(a3.swapaxes(1, 2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [ ]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [ ]:
print(n1)
print(n1[np.newaxis, :5]) #row에 축 추가
print(n1[:5, np.newaxis]) #column에 축 추가

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [ ]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5, 2))
print(n2)

[[7 0 7 9 5]
 [1 1 6 4 1]]
[[7 0]
 [7 9]
 [5 1]
 [1 6]
 [4 1]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [ ]:
n2.resize((5, 5))
print(n2)

[[7 0 7 9 5]
 [1 1 6 4 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [ ]:
n2.resize((3, 3))
print(n2)

[[7 0 7]
 [9 5 1]
 [1 6 4]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [ ]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [ ]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [ ]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [ ]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [ ]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [ ]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
np.concatenate([a2, a2]) #default: axis=0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [ ]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [ ]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [ ]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [ ]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [ ]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5]) #기준 인덱스
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [ ]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [ ]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(a1 + a2)

b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)
print(a1 + b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [ ]:
a1 = np.arange(1, 10)
print(a1)
print(a1 + 1)
print(np.add(a1, 10))
print(a1 - 2)
print(np.subtract(a1, 10))
print(-a1)
print(np.negative(a1))
print(a1 * 2)
print(np.multiply(a1, 2))
print(a1 / 2)
print(np.divide(a1, 2))
print(a1 // 2)
print(np.floor_divide(a1, 2))
print(a1 ** 2)
print(np.power(a1, 2))
print(a1 % 2)
print(np.mod(a1, 2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [ ]:
a1 = np.arange(1, 10)
print(a1)
b1 = np.random.randint(1, 10, size=9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[5 9 5 7 9 5 9 5 5]
[ 6 11  8 11 14 11 16 13 14]
[-4 -7 -2 -3 -4  1 -2  3  4]
[ 5 18 15 28 45 30 63 40 45]
[0.2        0.22222222 0.6        0.57142857 0.55555556 1.2
 0.77777778 1.6        1.8       ]
[0 0 0 0 0 1 0 1 1]
[       1      512      243    16384  1953125     7776 40353607    32768
    59049]
[1 2 3 4 5 1 7 3 4]


In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.random.randint(1, 10, size=(3, 3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 ** b2)
print(a2 % b2)
print(a2 // b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 2 9]
 [8 8 1]
 [5 9 5]]
[[ 5  4 12]
 [12 13  7]
 [12 17 14]]
[[-3  0 -6]
 [-4 -3  5]
 [ 2 -1  4]]
[[ 4  4 27]
 [32 40  6]
 [35 72 45]]
[[0.25       1.         0.33333333]
 [0.5        0.625      6.        ]
 [1.4        0.88888889 1.8       ]]
[[        1         4     19683]
 [    65536    390625         6]
 [    16807 134217728     59049]]
[[1 0 3]
 [4 5 0]
 [2 8 4]]
[[0 1 0]
 [0 0 6]
 [1 0 1]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [ ]:
a1 = np.random.randint(-10, 10, size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[ 3 -6  6  2 -7]
[3 6 6 2 7]
[3 6 6 2 7]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [ ]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1)) #sqrt: square root

[ 3 -6  6  2 -7]
[ 9 36 36  4 49]
[1.73205081        nan 2.44948974 1.41421356        nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 지수와 로그 함수 (Exponential and Log Function)

In [ ]:
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[7 9 1 5 7]
[1.09663316e+03 8.10308393e+03 2.71828183e+00 1.48413159e+02
 1.09663316e+03]
[128. 512.   2.  32. 128.]
[49 81  1 25 49]


In [ ]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[7 9 1 5 7]
[1.94591015 2.19722458 0.         1.60943791 1.94591015]
[2.80735492 3.169925   0.         2.32192809 2.80735492]
[0.84509804 0.95424251 0.         0.69897    0.84509804]


#### 삼각 함수(Trigonometrical Function)


In [ ]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [ ]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[6 4 2]
 [6 1 8]
 [1 7 8]]
43 43
[13 12 18] [13 12 18]
[12 15 16] [12 15 16]


#### cumsum(): 누적합 계산

In [ ]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[2 2 7]
 [7 2 9]
 [8 5 5]]
[ 2  4 11 18 20 29 37 42 47]
[[ 2  2  7]
 [ 9  4 16]
 [17  9 21]]
[[ 2  4 11]
 [ 7  9 18]
 [ 8 13 18]]


#### diff(): 차분 계산

In [ ]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[7 8 9]
 [4 3 4]
 [6 8 1]]
[[ 1  1]
 [-1  1]
 [ 2 -7]]
[[-3 -5 -5]
 [ 2  5 -3]]
[[ 1  1]
 [-1  1]
 [ 2 -7]]


#### prod(): 곱 계산

In [ ]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[7 6 8]
 [1 2 1]
 [2 9 4]]
48384
[ 14 108  32]
[336   2  72]


#### cumprod(): 누적곱 계산

In [ ]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[4 3 3]
 [9 8 8]
 [7 5 1]]
[     4     12     36    324   2592  20736 145152 725760 725760]
[[  4   3   3]
 [ 36  24  24]
 [252 120  24]]
[[  4  12  36]
 [  9  72 576]
 [  7  35  35]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [ ]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2)) #matmul: matrix multiply

[[4 3 3]
 [9 8 8]
 [7 5 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[10 10 10]
 [25 25 25]
 [13 13 13]]
[[10 10 10]
 [25 25 25]
 [13 13 13]]


#### tensordot(): 텐서곱 계산

In [ ]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[4 3 3]
 [9 8 8]
 [7 5 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
48
[[[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]]
[[10 10 10]
 [25 25 25]
 [13 13 13]]


#### cross(): 벡터곱

In [ ]:
x = [1, 2, 3]
y = [4, 5, 6]
print(np.cross(x, y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [ ]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[4 3 3]
 [9 8 8]
 [7 5 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[10 10 10]
 [25 25 25]
 [13 13 13]]
[[4 4 4 4 4 4 4 4 4]
 [3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3]
 [9 9 9 9 9 9 9 9 9]
 [8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 7 7]
 [5 5 5 5 5 5 5 5 5]
 [1 1 1 1 1 1 1 1 1]]


#### mean(): 평균 계산

In [ ]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[4 3 3]
 [9 8 8]
 [7 5 1]]
5.333333333333333
[6.66666667 5.33333333 4.        ]
[3.33333333 8.33333333 4.33333333]


#### std(): 표준 편차 계산

In [ ]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[4 3 3]
 [9 8 8]
 [7 5 1]]
2.6246692913372702
[2.05480467 2.05480467 2.94392029]
[0.47140452 0.47140452 2.49443826]


#### var(): 분산 계산

In [ ]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[4 3 3]
 [9 8 8]
 [7 5 1]]
6.888888888888889
[4.22222222 4.22222222 8.66666667]
[0.22222222 0.22222222 6.22222222]


#### min(): 최소값

In [ ]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[4 3 3]
 [9 8 8]
 [7 5 1]]
1
[4 3 1]
[3 8 1]


#### max(): 최대값

In [ ]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[4 3 3]
 [9 8 8]
 [7 5 1]]
9
[9 8 8]
[4 9 7]


#### argmin(): 최소값 인덱스

In [ ]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[4 3 3]
 [9 8 8]
 [7 5 1]]
8
[0 0 2]
[1 1 2]


#### argmax(): 최대값 인덱스

In [ ]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[4 3 3]
 [9 8 8]
 [7 5 1]]
3
[1 1 1]
[0 0 0]


#### median(): 중앙값

In [ ]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[4 3 3]
 [9 8 8]
 [7 5 1]]
5.0
[7. 5. 3.]
[3. 8. 5.]


#### percentile(): 백분위 수



In [ ]:
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [ ]:
a2 = np.array([[False, False, False], 
               [False, True, True], 
               [False, True, True]])
print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [ ]:
a2 = np.array([[False, False, True], 
               [True, True, True], 
               [False, True, True]])
print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)


In [ ]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))
print(np.any(a2 > 5))
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))
print(np.all(a2 > 5))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1)) #isclose(): 가까운지

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [ ]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF]) #inf: 무한대 #NINF: negative infinite 마이너스 무한대
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)])

print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)])

print((a2 > 5) ^ (a2 < 8)) # ^: XOR
print(a2[(a2 > 5) ^ (a2 < 8)])

print(~(a2 > 5))
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [ ]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1))
print(a1) #원본 배열 유지
print(np.argsort(a1)) #argsort(): 정렬 시 와야 할 인덱스
print(a1) #원본 배열 유지
print(a1.sort())
print(a1) #원본 배열 변경

[4 7 3 8 2 1 4 1 3 5]
[1 1 2 3 3 4 4 5 7 8]
[4 7 3 8 2 1 4 1 3 5]
[5 7 4 2 8 0 6 9 1 3]
[4 7 3 8 2 1 4 1 3 5]
None
[1 1 2 3 3 4 4 5 7 8]


In [ ]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[9 8 8]
 [9 1 7]
 [7 1 5]]
[[7 1 5]
 [9 1 7]
 [9 8 8]]
[[8 8 9]
 [1 7 9]
 [1 5 7]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [ ]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1, 3))

[9 9 2 7 7 3 8 9 5 2]
[2 2 3 5 7 9 8 9 7 9]


In [ ]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))

[[6 2 3 8 3]
 [9 4 8 2 7]
 [6 4 9 6 7]
 [7 7 1 6 9]
 [5 9 5 3 9]]
[[2 3 3 6 8]
 [2 7 4 8 9]
 [6 6 4 7 9]
 [6 1 7 7 9]
 [3 5 5 9 9]]
[[5 2 1 2 3]
 [6 4 3 3 7]
 [6 4 5 6 7]
 [7 7 8 6 9]
 [9 9 9 8 9]]
[[2 3 3 6 8]
 [2 7 4 8 9]
 [6 6 4 7 9]
 [6 1 7 7 9]
 [3 5 5 9 9]]


## 배열 입출력


In [ ]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
np.save("a", a2) #np.save("파일이름", 배열)

[[3 6 4 2 6]
 [9 3 8 5 2]
 [4 5 7 9 9]
 [6 2 4 6 8]
 [9 9 4 5 7]]


In [ ]:
!ls #.npy: 확장자, 바이너리 파일로 저장

a.npy  sample_data


In [ ]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez("ab", a2, b2)

[[5 1 1 6 2]
 [1 2 7 7 2]
 [5 1 7 4 7]
 [2 9 6 2 3]
 [3 4 1 5 2]]


In [ ]:
!ls #.npz: 여러 개 배열 저장한 파일의 확장자

ab.npz	a.npy  sample_data


In [ ]:
npy = np.load("a.npy")
print(npy)

[[3 6 4 2 6]
 [9 3 8 5 2]
 [4 5 7 9 9]
 [6 2 4 6 8]
 [9 9 4 5 7]]


In [ ]:
npz = np.load("ab.npz")
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[3 6 4 2 6]
 [9 3 8 5 2]
 [4 5 7 9 9]
 [6 2 4 6 8]
 [9 9 4 5 7]]
[[5 1 1 6 2]
 [1 2 7 7 2]
 [5 1 7 4 7]
 [2 9 6 2 3]
 [3 4 1 5 2]]


In [ ]:
print(a2)
np.savetxt("a.csv", a2, delimiter=',') #csv: comma seperated values, 구분자(delimiter)는 콤마

[[3 6 4 2 6]
 [9 3 8 5 2]
 [4 5 7 9 9]
 [6 2 4 6 8]
 [9 9 4 5 7]]


In [ ]:
!ls

ab.npz	a.csv  a.npy  sample_data


In [ ]:
!cat a.csv #텍스트형태로 저장하기 때문에 데이터타입 지정 못해서 실수 형태로 출력됨

3.000000000000000000e+00,6.000000000000000000e+00,4.000000000000000000e+00,2.000000000000000000e+00,6.000000000000000000e+00
9.000000000000000000e+00,3.000000000000000000e+00,8.000000000000000000e+00,5.000000000000000000e+00,2.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,7.000000000000000000e+00,9.000000000000000000e+00,9.000000000000000000e+00
6.000000000000000000e+00,2.000000000000000000e+00,4.000000000000000000e+00,6.000000000000000000e+00,8.000000000000000000e+00
9.000000000000000000e+00,9.000000000000000000e+00,4.000000000000000000e+00,5.000000000000000000e+00,7.000000000000000000e+00


In [ ]:
csv = np.loadtxt("a.csv", delimiter=',') #구분자에 따라 분리시켜 배열 불러와 출력
print(csv)

[[3. 6. 4. 2. 6.]
 [9. 3. 8. 5. 2.]
 [4. 5. 7. 9. 9.]
 [6. 2. 4. 6. 8.]
 [9. 9. 4. 5. 7.]]


In [ ]:
print(b2)
np.savetxt("b.csv", b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5')
#fmt(format 옵션): 소수점 이하 자리수 지정하여 저장
#header: 상단 column명

[[5 1 1 6 2]
 [1 2 7 7 2]
 [5 1 7 4 7]
 [2 9 6 2 3]
 [3 4 1 5 2]]


In [ ]:
!cat b.csv

# c1, c2, c3, c4, c5
5.00e+00,1.00e+00,1.00e+00,6.00e+00,2.00e+00
1.00e+00,2.00e+00,7.00e+00,7.00e+00,2.00e+00
5.00e+00,1.00e+00,7.00e+00,4.00e+00,7.00e+00
2.00e+00,9.00e+00,6.00e+00,2.00e+00,3.00e+00
3.00e+00,4.00e+00,1.00e+00,5.00e+00,2.00e+00


In [ ]:
csv = np.loadtxt("b.csv", delimiter=',')
print(csv)

[[5. 1. 1. 6. 2.]
 [1. 2. 7. 7. 2.]
 [5. 1. 7. 4. 7.]
 [2. 9. 6. 2. 3.]
 [3. 4. 1. 5. 2.]]




---

